apiVersion: v1
kind: Service
metadata:
    name: "mytcsaskcluster-0487"
    labels:
        app: "mytcsaskcluster-0487"
spec:
    type: LoadBalancer
    ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http
    selector:
        app: "mytcsaskcluster-0487"