on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    
    - uses: actions/checkout@master
    
    - uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Create ACR
      id: create-acr
      run: |
        az acr create -n myacr202223 -g myacr2022239b44-rg --location "East US" --sku Standard --admin-enabled
        echo "::set-output name=acr_username::`az acr credential show -n myacr202223 --query username | xargs`"
        echo "::set-output name=acr_password::`az acr credential show -n myacr202223 --query passwords[0].value | xargs`"
        echo "::add-mask::`az acr credential show -n myacr202223 --query passwords[0].value | xargs`"

    - uses: azure/docker-login@v1
      with:
        login-server: myacr202223.azurecr.io
        username: ${{ steps.create-acr.outputs.acr_username }}
        password: ${{ steps.create-acr.outputs.acr_password }}

    - name: Build and push image to ACR
      id: build-image
      run: |
        docker build "$GITHUB_WORKSPACE/result" -f  "result/Dockerfile" -t myacr202223.azurecr.io/mytcsaskcluster:${{ github.sha }} --label dockerfile-path=result/Dockerfile
        docker push myacr202223.azurecr.io/mytcsaskcluster:${{ github.sha }}
    
    - uses: azure/k8s-set-context@v1
      id: login
      with:
         kubeconfig: ${{ secrets.aks_mytcsaskcluster_kubeConfig }}
    
    - name: Create namespace
      run: |
        namespacePresent=`kubectl get namespace | grep mytcsaskcluster8c30-voting-app | wc -l`
        if [ $namespacePresent -eq 0 ]
        then
            echo `kubectl create namespace mytcsaskcluster8c30-voting-app`
        fi

    - uses: azure/k8s-create-secret@v1
      with:
        namespace: mytcsaskcluster8c30-voting-app
        container-registry-url: myacr202223.azurecr.io
        container-registry-username: ${{ steps.create-acr.outputs.acr_username }}
        container-registry-password: ${{ steps.create-acr.outputs.acr_password }}
        secret-name: mytcsaskclusdockerauth
       
    - uses: azure/k8s-deploy@v1.2
      with:
        namespace: mytcsaskcluster8c30-voting-app
        manifests: |
          manifests/deployment-18.yml
          manifests/service-18.yml
        images: |
          myacr202223.azurecr.io/mytcsaskcluster:${{ github.sha }}
        imagepullsecrets: |
          mytcsaskclusdockerauth   
