on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    
    - uses: actions/checkout@master
    
    - uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Create ACR
      id: create-acr
      run: |
        az acr create -n myacr202222 -g myacr202222bee1-rg --location "East US" --sku Standard --admin-enabled
        echo "::set-output name=acr_username::`az acr credential show -n myacr202222 --query username | xargs`"
        echo "::set-output name=acr_password::`az acr credential show -n myacr202222 --query passwords[0].value | xargs`"
        echo "::add-mask::`az acr credential show -n myacr202222 --query passwords[0].value | xargs`"

    - uses: azure/docker-login@v1
      with:
        login-server: myacr202222.azurecr.io
        username: ${{ steps.create-acr.outputs.acr_username }}
        password: ${{ steps.create-acr.outputs.acr_password }}

    - name: Build and push image to ACR
      id: build-image
      run: |
        docker build "$GITHUB_WORKSPACE/result" -f  "result/Dockerfile" -t myacr202222.azurecr.io/myakscluster:${{ github.sha }} --label dockerfile-path=result/Dockerfile
        docker push myacr202222.azurecr.io/myakscluster:${{ github.sha }}
    
    - uses: azure/k8s-set-context@v1
      id: login
      with:
         kubeconfig: ${{ secrets.aks_myakscluster_kubeConfig }}
    
    - name: Create namespace
      run: |
        namespacePresent=`kubectl get namespace | grep myaksclusterb9a0-votingapp | wc -l`
        if [ $namespacePresent -eq 0 ]
        then
            echo `kubectl create namespace myaksclusterb9a0-votingapp`
        fi

    - uses: azure/k8s-create-secret@v1
      with:
        namespace: myaksclusterb9a0-votingapp
        container-registry-url: myacr202222.azurecr.io
        container-registry-username: ${{ steps.create-acr.outputs.acr_username }}
        container-registry-password: ${{ steps.create-acr.outputs.acr_password }}
        secret-name: myaksclusterdockerauth
       
    - uses: azure/k8s-deploy@v1.2
      with:
        namespace: myaksclusterb9a0-votingapp
        manifests: |
          manifests/deployment-17.yml
          manifests/service-17.yml
        images: |
          myacr202222.azurecr.io/myakscluster:${{ github.sha }}
        imagepullsecrets: |
          myaksclusterdockerauth   
